from .job import router as job_router
from .story import router as story_router
from .auth import router as auth_router
from .like import router as like_router
from .comment import router as comment_router
from .follow import router as follow_router
from .feed import router as feed_router
from .notification import router as notification_router
from .analytics import router as analytics_router
from .user import router as user_router
from .bookmark import router as bookmark_router
from .message import router as message_router
from .template import router as template_router